### ISSUE TITLE
Add community metrics from GitHub API

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/aggregit#5]
The `https://api.github.com/repos/:owner/:repo/community/profile` API endpoint provides the following dataset:

```JS
{
  "health_percentage": 100,
  "description": "My first repository on GitHub!",
  "documentation": true,
  "files": {
    "code_of_conduct": {
      "name": "Contributor Covenant",
      "key": "contributor_covenant",
      "url": "https://api.github.com/codes_of_conduct/contributor_covenant",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/CODE_OF_CONDUCT.md"
    },
    "contributing": {
      "url": "https://api.github.com/repos/octocat/Hello-World/contents/CONTRIBUTING",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/CONTRIBUTING"
    },
    "issue_template": {
      "url": "https://api.github.com/repos/octocat/Hello-World/contents/ISSUE_TEMPLATE",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/ISSUE_TEMPLATE"
    },
    "pull_request_template": {
      "url": "https://api.github.com/repos/octocat/Hello-World/contents/PULL_REQUEST_TEMPLATE",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/PULL_REQUEST_TEMPLATE"
    },
    "license": {
      "name": "MIT License",
      "key": "mit",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/LICENSE"
    },
    "readme": {
      "url": "https://api.github.com/repos/octocat/Hello-World/contents/README.md",
      "html_url": "https://github.com/octocat/Hello-World/blob/master/README.md"
    }
  },
  "updated_at": "2017-02-28T19:09:29Z"
}
```

This data can be used to monitor the existence of docs and overall community health.

**Comment by MichaelJolley** [comment]
@lornajane, I'd love your feedback on this.  Currently, I've updated the action to record new information like so:

```JS
...
    healthPercentage: {
        '2020-04-14': 64,
        '2020-04-15': 83
    },
    codeOfConductExists: {
        '2020-04-14': false,
        '2020-04-15': true
    },
    contributingExists: {
        '2020-04-14': true,
        '2020-04-15': true
    },
    issueTemplateExists: {
        '2020-04-14': false,
        '2020-04-15': false
    },
    pullRequestTemplateExists: {
        '2020-04-14': false,
        '2020-04-15': true
    },
    licenseExists: {
        '2020-04-14': true,
        '2020-04-15': true
    },
    readMeExists: {
        '2020-04-14': true,
        '2020-04-15': true
    }
}
```

My question relates to the documents that it's tracking.  Is that something we should necessarily track across time or could we just have a generic boolean for each.

Example:

```JS
...
    healthPercentage: {
        '2020-04-14': 64,
        '2020-04-15': 83
    },
    codeOfConductExists: true,
    contributingExists: true,
    issueTemplateExists: false,
    pullRequestTemplateExists: true,
    licenseExists: false,
    readMeExists: true
}
```

**Comment by MichaelJolley** [comment]
@mheap / @dragonmantank, I'd love to get your opinions on this as well.

**Comment by lornajane** [comment]
I think over time is useful if we want to show our progress to the business. Could we collect all the data as repo/date combinations? Then I could get just the data for March, for example. Also it may make it easier to archive data older than 2 years or something. I would only pull the fields we care most about though, and I'll propose that those are:
 - the README
 - the license
 - the code of conduct
 - the contributing file
 - the overall health score

GitHub thinks templates are important but as a company, I don't think our processes are at the stage where they are useful. I know they go into the score calculation but I don't think the templates are useful for any of our repos.

**Comment by MichaelJolley** [comment]
@lornajane my primary question wasn't defined because I needed sleep. 😄 

The question is specific to the documents.  Is there a benefit to track day by day if the repo had a README or just a boolean that it does or does not today.  

The health percentage and all other metrics are tracked on a daily basis.

**Comment by mheap** [comment]
I think showing that there's been a change is state is useful, but not day by day. Could we log whenever a state change occurs? e.g.

```
codeOfConductExists: {
    '2020-04-14': false,
    '2020-04-16': true,
    '2020-04-20': false
},
```

Rather than:

```
codeOfConductExists: {
    '2020-04-14': false,
    '2020-04-15': false,
    '2020-04-16': true,
    '2020-04-17': true,
    '2020-04-18': true,
    '2020-04-19': true,
    '2020-04-20': false
},
```

**Comment by dragonmantank** [comment]
I agree with @mheap, the document statuses would be better tracked as changes with timestamps versus a daily check-in to see if they exist. Otherwise we'll end up with hundreds of lines of "true" which doesn't get us anything.
